### PR TITLE
RC #173 - Documentation

### PR DESCRIPTION
**Pull request by dleadbetter**
This pull request implements a framework for more comprehensive documentation of the components available in the `react-components` library. The framework is built upon the Storybook Docs Addon framework, and will use MDX syntax to allow developers to document component APIs. 

The framework will also use [react-docgen](https://github.com/reactjs/react-docgen) to parse source code, pulling out component and prop JSDoc comments.

#### MyComponent.js
```
type Props = {
  /**
   * This is a comment for prop1.
   */
  prop1: string,

  /**
   * This is a comment for prop2.
   */
  prop2?: number
};

/**
 * This is the header comment. 
 */
const MyComponent = (props: Props) => (
  <div>{ renderSomething() }</div>
);

export default MyComponent;
```

#### MyComponent.stories.mdx
```
import MyComponent from './MyComponent';

<DocHeader
  item={MyComponent}
/>

# This is my new component

# Here's the props table for my new component

<PropsTable
  item={MyComponent}
/>

## Here's some more information about the component...
```

Screen Shot 2022-10-21 at 9 18 07 AM

### CODE REVIEW

**Review by jamiefolsom — APPROVED** [review]
Great solution! If the Peripleo/Same Boats team likes this approach, let's discuss your idea of making it importable by other projects. 👍🏻 cc @rsimon and @blms

**Review by camdendotlol — APPROVED** [review]
Looks good to me, I like this design

**Comment by dleadbetter** [comment]
Changes should be visible at: https://performant-software.github.io/react-components

**Comment by NickLaiacona** [comment]
This is very cool and seems very complete. A few things I noticed:

* `ListTable` - the docs here refer to the `DataList` higher order component, but I don't see that on the list. Did you mean `DataView`?
* `FileUploadModal` - the modal background screen in the example component is obscuring the documentation.
* `DataView` - don't see a description of the props for this one.

**Comment by dleadbetter** [comment]
> * `ListTable` - the docs here refer to the `DataList` higher order component, but I don't see that on the list. Did you mean `DataView`?

The `DataList` is a higher order component that provides API fetching functionality (sorting, filtering, pagination, crud operations, etc), but doesn't actually render any DOM. It's the basis for both the `ListTable` and `ItemList` components.

My thought was that it could be confusing to includes stories for higher-order components that don't render anything, since it will really be up to the developer to determine what the component that uses the HOC will look like.

All of the props that can be passed to the `DataList` are also included in the list of props for components that use it.

> * `FileUploadModal` - the modal background screen in the example component is obscuring the documentation.

Ahh, nice catch. This should now be fixed. Since all of the stories display on the "Docs" tab, we'll have to be conscious about any absolutely positioned elements.

> * `DataView` - don't see a description of the props for this one.

This one was on the initial list you sent over, but I'm not sure it's a great candidate for the first set of components to document, as I suspect it will be used infrequently.

This component was designed for a project (CFRP I believe, but @jamiefolsom  would be able to confirm) that essentially wanted to see a read-only view of their database in an HTML format. It's designed to be used as part of the [database-explorer](https://github.com/performant-software/database-explorer) application, which can essentially connect to a database via SSH and on the front end will render a side or top menu with table names and show the content of the currently selected table.

**Review by NickLaiacona — APPROVED** [review]
Nice job

**Pull request merged**
